name = "Aeropp"
author = "kingpw and contributors"
version = "0.1.0"
description = "Aeropp：Minecraft 1.21.1 + NeoForge 的联合开发整合包。"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87176cee1ebf42b44824ec00507098328da4a9f6a553beedffcf9e66c3c67783"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
meta-folder = "mods"
