name = "Aeropp"
author = "kingpw and contributors"
version = "0.1.0"
description = "Aeropp：Minecraft 1.21.1 + NeoForge 的联合开发整合包。"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b1622e5ac2daea369d8ba3e2ee4fbfc2179791a1b1b70d5cd329f7b674ba414"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
meta-folder = "mods"
