name = "Aeropp"
author = "kingpw and contributors"
version = "0.1.0"
description = "Aeropp：Minecraft 1.21.1 + NeoForge 的联合开发整合包。"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "599ac31b9daa91b1f3861c1859db031b399b3882f4dba0d2cbf557615687bef6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
meta-folder = "mods"
