org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
neoforge_version=21.1.248

create_modrinth_version=UjX6dr61
create_jetpack_modrinth_version=sCwiqLqq

mod_id=testmod
mod_name=Test Mod
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.testmod
mod_authors=Aeropp Team
mod_description=Experimental combat content imported into the Aeropp development workspace.
