# -----------------------------------------------------------------------------------
# Zombies Break & Build config
#
# This config can be reloaded with /reload
# You do NOT need to restart the server for most changes
#
# Note:
# Existing mobs may keep already-added AI goals until they respawn or are reloaded,
# but config values themselves are reloaded by /reload
# -----------------------------------------------------------------------------------

[blocks]
	# Block used when zombies build
	placeBlockId = "minecraft:dirt"

	# Blocks that zombies will consider dangerous and attempt to build on or break
	dangerousBlockIdList = ["minecraft:fire", "minecraft:soul_fire", "minecraft:campfire", "minecraft:soul_campfire", "minecraft:cactus", "minecraft:magma_block", "minecraft:sweet_berry_bush", "minecraft:wither_rose", "minecraft:powder_snow", "minecraft:lava", "minecraft:cobweb"]

[ai]
	# Zombies can see the nearest player no matter what.
	alwaysSeeNearestPlayer = false

	# Zombies can notice targets through walls
	canNoticeTargetsThroughBlocks = true

	# (only if canNoticeTargetsThroughBlocks is true) How many solid blocks can be between zombie and target when noticing through walls (0 - infinity)
	noticeTargetsThroughBlocksLimit = 3

	# Zombies can continue seeing targets through walls
	canContinueSeeingTargetsThroughBlocks = true

	# Gives all monsters, not just zombies, the ability to break and place blocks
	applyToAllMonsters = true

	# Additional entity IDs that will be given the ability to break and place blocks (only Pathfinder mobs)
	additionalEntityIdList = []

	# Entity IDs that will NOT be given the ability to place blocks
	ignoreBuildEntityIdList = ["minecraft:ender_dragon", "minecraft:ghast", "minecraft:phantom", "minecraft:blaze", "minecraft:vex", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:shulker", "minecraft:wither", "minecraft:breeze"]

	# Entity IDs that will NOT be given the ability to break blocks
	ignoreBreakEntityIdList = ["minecraft:ender_dragon", "minecraft:shulker", "minecraft:wither", "minecraft:vex"]

[balance]
	# Time during which zombies cannot break blocks they just placed (seconds)
	builtBlocksProtectionTime = 0.75

	# The radius within which zombies will detect dangerous blocks
	dangerousBlocksSearchRadius = 1

	# Distance to path end before breaking or building
	pathEndBreakBuildDistance = 6

	# How long block damage data is stored (seconds)
	damageStoreTime = 60.0

	[balance.blockDamage]
		# Damage dealt to blocks
		damageToBlocks = 3

		# How strongly the tool-in-hand damage multiplier affects block damage (0 - tools do not affect damage)
		itemDamageMultiplierStrength = 0.5

		# How strongly the hitbox size multiplier affects block damage (0 - hitbox size does not affect damage)
		hitboxSizeMultiplierStrength = 0.5

	[balance.cooldowns]
		# Cooldown between block breaking attempts (seconds)
		breakCooldown = 1.0

		# Cooldown between block placing attempts (seconds)
		buildCooldown = 1.0

		# Cooldown between searches for dangerous blocks (seconds)
		searchDangerousBlocksCooldown = 1.0

[blockRestoration]
	# Enable disappearing of blocks placed by zombies
	builtBlocksDisappearing = false

	# Time before placed blocks by zombies disappear (only if builtBlocksDisappearing is true)
	builtBlocksDisappearTime = 30.0

	# Enable restoration of blocks broken by zombies
	brokenBlocksRestoring = false

	# Time before broken blocks by zombies are restored (only if brokenBlocksRestoring is true)
	brokenBlocksRestoreTime = 30.0

[visualEffects]
	# [Break] Whether the zombie will swing when breaking a block
	breakMobSwing = true

	# [Build] Whether a placed block will play a sound
	buildBlockSound = true

	# [BrokenReappear] Whether a reappearing broken block will spawn particles
	brokenReappearParticles = true

	# [BrokenReappear] Whether a reappearing broken block will play a charge sound
	brokenReappearChargeSound = true

	# [BrokenReappear] Whether a reappearing broken block will play a sound
	brokenReappearSound = true

	# [BuiltDisappear] Whether a disappearing built block will spawn a block display
	builtDisappearBlockDisplay = true

	# [BuiltDisappear] Whether a disappearing built block will play a shrink sound
	builtDisappearShrinkSound = true

	# [BuiltDisappear] Whether a disappearing built block will play a sound
	builtDisappearSound = true
